# mise use python@3.13

[tools]
pre-commit = "latest"
python = "3.13"
trivy = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = "create|source"
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'study-app'
GITOPS_REPO = 'study-app-gitops'

[hooks]
enter = "bash ./scripts/setup_project"
